Add .sh env hook for setting GZ_CONFIG_PATH
gazebo-release/gz_common_vendor pull request #5
Opened 2024-10-08 14:35 UTC by nwn

For systems not using colcon's or ament's `.dsv` files for initializing the environment, having only "dummy" `.sh` hooks means that the `GZ_CONFIG_PATH` environment variable does not get set correctly. The proposed change is to define a "real" `.sh` hook with the proper logic to initialize the environment.

The same issue applies to many of the `gz_*_vendor` packages and I can create similar PRs for them, but wanted to get feedback from maintainers first to avoid potential spamming.

2024-10-15 18:18 UTC, nwn commented
@azeey Is the CI for this package working correctly? The above failure seems unrelated to these changes.

2024-10-17 19:50 UTC, azeey commented
The Jazzy build shouldn't be running for this branch. Fix in https://github.com/ros/rosdistro/pull/43231

2024-10-17 20:02 UTC, azeey requested changes
The approach seems good to me, but this file is automatically generated and should not be modified directly. Could you please close this PR and open one on https://github.com/gazebo-tooling/gz_vendor?

2024-10-17 23:04 UTC, nwn commented
Ah, I didn't realize these were all automatically generated. I've opened a new PR on the other repo as requested: https://github.com/gazebo-tooling/gz_vendor/pull/11.

2024-10-17 23:04 UTC, closed without merging